{{- if .Values.prometheusMetrics.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  endpoints:
  - interval: 10s
    port: metrics
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      metrics: "true"
{{- end }}
